[package]
name = "huey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.11.3"
image = "0.24.1"
rayon = "1.5.1"